# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Patient UI kit
email: james.gilyead@clearleft.com
description: "This page demonstrates the basic styles of the evolving Patient brand."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Colours
sets:
  - name: Core
    colours:
      - name: blue
        hex:  "#009BF5"
      - name: navy
        hex:  "#0F2E4C"

  - name: Neutral
    colours:
      - name: white
        hex: "#FFFFFF"
      - name: grey
        hex:  "#EEEEEE"
      - name: black
        hex:  "#333333"

  - name: Extended
    colours:
      - name: red
        hex:  "#FF3344"
      - name: orange
        hex:  "#FF7F00"
      - name: yellow
        hex:  "#FFD500"
      - name: green
        hex:  "#44AB11"
      - name: teal
        hex:  "#00D9BC"
      - name: purple
        hex:  "#7F66FF"
      - name: violet
        hex:  "#C24CD9"
      - name: pink
        hex:  "#FF4C9D"
